[package]
name = "dbc-client-rpc-debug"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"

[dependencies]
futures = { workspace = true, features = [ "compat" ] }
hex-literal = { workspace = true }
jsonrpsee = { workspace = true, features = [ "macros", "server" ] }
tokio = { workspace = true, features = [ "sync", "time" ] }

dbc-client-evm-tracing = { workspace = true }
dbc-client-rpc-core-debug = { workspace = true }
dbc-client-rpc-core-types = { workspace = true }
dbc-primitives-rpc-debug = { workspace = true, features = [ "std" ] }

# Substrate
sc-client-api = { workspace = true }
sc-utils = { workspace = true }
sp-api = { workspace = true, features = [ "std" ] }
sp-block-builder = { workspace = true, features = [ "std" ] }
sp-blockchain = { workspace = true }
sp-core = { workspace = true, features = [ "std" ] }
sp-io = { workspace = true, features = [ "std" ] }
sp-runtime = { workspace = true, features = [ "std" ] }

# Frontier
ethereum = { workspace = true, features = [ "std", "with-codec" ] }
ethereum-types = { workspace = true, features = [ "std" ] }
fc-consensus = { workspace = true }
fc-db = { workspace = true }
fc-rpc = { workspace = true, features = [ "rpc-binary-search-estimate" ] }
fc-storage = { workspace = true }
fp-rpc = { workspace = true, features = [ "std" ] }
