[package]
name = "dbc-client-rpc-core-txpool"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"

[dependencies]
ethereum = { workspace = true, features = [ "std", "with-codec" ] }
ethereum-types = { workspace = true, features = [ "std" ] }
jsonrpsee = { workspace = true, features = [ "macros", "server" ] }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }

fc-rpc-core = { workspace = true }
