[package]
name = "dbc-evm-tracer"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"

[dependencies]

# DBC
dbc-primitives-rpc-evm-tracing-events = { workspace = true, features = [ "evm-tracing" ] }
dbc-primitives-ext = { workspace = true }

# Substrate
parity-scale-codec = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Frontier
ethereum-types = { workspace = true }
evm = { workspace = true }
evm-gasometer = { workspace = true }
evm-runtime = { workspace = true }
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = [ "forbid-evm-reentrancy" ] }

[features]
default = [ "std" ]
std = [
	"ethereum-types/std",
	"evm-gasometer/std",
	"evm-runtime/std",
	"dbc-primitives-rpc-evm-tracing-events/std",
	"evm/std",
	"evm/with-serde",
	"fp-evm/std",
	"dbc-primitives-ext/std",
	"pallet-evm/std",
	"parity-scale-codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
