[package]
name = "rent-dlc-machine-rpc"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true }
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }

dbc-support = { path = "../../support" }
rent-dlc-machine-runtime-api = { path = "./runtime-api" }

sp-api = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-blockchain = { workspace = true }
