[package]
name = "terminating-rental-runtime-api"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true }

sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

dbc-support = { path = "../../../support", default-features = false }
terminating-rental = { path = "../../../terminating-rental", default-features = false }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "terminating-rental/std",
  "sp-api/std",
  "sp-runtime/std",
  "sp-std/std",
  "dbc-support/std",
]
