[package]
name = "pallet-staking-reward-fn"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]

[dependencies]
log = { workspace = true }
sp-arithmetic = { workspace = true }

[features]
default = ["std"]
std = [
	"log/std",
	"sp-arithmetic/std",
]
