[package]
name = "pallet-staking-runtime-api"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true }
sp-api = { workspace = true }

[features]
default = ["std"]
std = ["parity-scale-codec/std", "sp-api/std"]
