[package]
name = "online-committee-runtime-api"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true }
online-committee = { path = "../../../online-committee", default-features = false }
dbc-support = { path = "../../../support", default-features = false }

sp-api = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "online-committee/std",
  "sp-api/std",
  "sp-runtime/std",
  "dbc-support/std",
]
