[package]
name = "pallet-scheduler"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"
repository = { workspace = true }

[dependencies]
parity-scale-codec = { workspace = true }
log = { workspace = true }
scale-info = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
pallet-preimage = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
substrate-test-utils = { workspace = true }

[features]
default = ["std"]
# runtime-benchmarks = [
# 	"frame-benchmarking",
# 	"frame-support/runtime-benchmarks",
# 	"frame-system/runtime-benchmarks",
# ]
std = [
	"parity-scale-codec/std",
	# "frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = ["frame-support/try-runtime"]
