[package]
name = "simple-rpc-rpc"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true }
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }
dbc-support = { path = "../../support", default-features = false }
simple-rpc = { path = "../../simple-rpc", default-features = false }
simple-rpc-runtime-api = { path = "./runtime-api", default-features = false }

sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }

[features]
default = ["std"]
std = ["sp-api/std", "sp-runtime/std", "dbc-support/std"]
