[package]
authors = ["bobo <dongkaige@gmail.com>"]
edition = "2021"
name = "simple-rpc-rpc"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
dbc-support = { version = "0.1.0", path = "../../support", default-features = false }
simple-rpc = { version = "0.1.0", path = "../../simple-rpc", default-features = false }
simple-rpc-runtime-api = { version = "0.1.0", path = "./runtime-api", default-features = false }

sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }

[features]
default = ["std"]
std = ["sp-api/std", "sp-runtime/std", "dbc-support/std"]
