[package]
name = "dbc-finality-rpc"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"
repository = { workspace = true }

[dependencies]
futures = { workspace = true, features = [ "compat" ] }
jsonrpsee = { workspace = true, features = [ "macros", "server" ] }
parity-scale-codec = { workspace = true, features = [ "std" ] }
tokio = { workspace = true, features = [ "sync", "time" ] }

fc-db = { workspace = true }
fc-rpc = { workspace = true }
sp-api = { workspace = true, features = [ "std" ] }
sp-blockchain = { workspace = true }
sp-core = { workspace = true, features = [ "std" ] }
sp-runtime = { workspace = true, features = [ "std" ] }
