[package]
name = "dbc-finality-rpc"
version = { workspace = true }
authors = { workspace = true }
edition = "2021"
repository = { workspace = true }

[dependencies]
jsonrpsee = { workspace = true, features = [ "macros", "server" ] }

fc-db = { workspace = true }
fc-rpc = { workspace = true }
sp-blockchain = { workspace = true }
sp-core = { workspace = true, features = [ "std" ] }
sp-runtime = { workspace = true, features = [ "std" ] }
