name: Publish Runtime

# The code (like generate-release-body) will be taken from the tag versions, not master
on:
  workflow_dispatch:
    inputs:
      version:
        description: runtime version (ex. 400)
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build-runtimes:
    runs-on: ubuntu-latest
    steps:
      - name: Set commit SHA
        run: echo "COMMIT_SHA8=${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: actions/checkout@v4

      # https://github.com/jlumbroso/free-disk-space
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - uses: dtolnay/rust-toolchain@master
        with:
           toolchain: nightly-2023-09-20
           components: rustfmt
      - name: Build runtime
        run: |
          make build-runtime
          cp target/release/wbuild/dbc-runtime/dbc_runtime.compact.compressed.wasm dbc-runtime-${{ env.VERSION }}-${{ env.COMMIT_SHA8 }}.wasm

      - name: Build evm tracing runtime
        run: |
          make build-evm-tracing-runtime
          cp target/release/wbuild/dbc-runtime/dbc_runtime.compact.compressed.wasm dbc-runtime-tracing-${{ env.VERSION }}-${{ env.COMMIT_SHA8 }}.wasm

      - name: Archive Artifacts for runtime
        uses: actions/upload-artifact@v4
        with:
          name: dbc-runtime-${{ env.VERSION }}-${{ env.COMMIT_SHA8 }}
          path: |
            dbc-runtime-${{ env.VERSION }}-${{ env.COMMIT_SHA8 }}.wasm
            dbc-runtime-tracing-${{ env.VERSION }}-${{ env.COMMIT_SHA8 }}.wasm
